### ISSUE TITLE
Example on the manual doesn't work

### ISSUE THREAD

**Issue by sdrdis** [NeoGeographyToolkit/StereoPipeline#147]
Hi,

The example at page 20 of the manual doesn't seem to work anymore.

I tried to go at the specified webpage (http://www.digitalglobe.com/resources/imagery-product-samples) and tried to get the India stereo images (http://www.digitalglobe.com/resources/imagery-product-samples/stereo-satellite-imagery). It was the only India stereo pair I found. The stereo image seems different from what you have on the manual. Folder names and file names are slightly different too... They probably changed the India sample...

First, `dg_mosaic` doesn't work because I suspect it needs a XML file for each image file, but the folder I have downloaded has only one XML file for each set of 4 images (R1C1, R1C2, R2C1, R2C2). As there is now two JPG images available in the folder that merge each set of 4 images, I used these JPG images instead for stereo...

Secondly, `stereo -t dg --subpixel-mode 1 --alignment-method affineepipolar <files...>` fails and displays:
`Couldn't find "TLCTIME" tag.XML file "test/14SEP08054111-P2AS-053950035010_01_P001.XML" is invalid.`
I tried removing the XML files from the command line, but I got the following error:
`terminate called after throwing an instance of 'xercesc_3_1::SAXParseException'`
However `stereo` works with `-t rpc`...

I think these issues are mainly due to the fact that the stereo images from DigitalGlobe changed, as well as how they format their XML file.

Could you provide the India stereo images you used in your manual?

Thanks,

**Comment by ScottMcMichael** [comment]
I think the problem here is that the new stereo images from India are from the GeoEye satellite which requires some different processing steps (there is an example later in the manual).  Other sample stereo images from WorldView satellites appear to be working correctly.  After I finish some runs to double check that everything works I will update our documentation to replace the missing example with one of their current offerings.
