### ISSUE TITLE
Seed-mode 3 does not work with alignment-method epipolar

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#153]
As the title says. Any IceBridge testcase should be a good example.  Affineepipolar works though.

**Comment by ScottMcMichael** [comment]
After some testing it looks like sparse_disp "works" for epipolar images but either the default parameters or the algorithms used do not get good results, at least for the images I tested on.  Since this isn't just a bug fix and will require more digging in to the sparse_disp algorithm I think it can wait until someone actually needs this functionality.  Certainly it is not needed for IceBridge.
