### ISSUE TITLE
Incorrect box union functionality

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#158]
I fixed two very gross bugs in VisionWorkbench, the union and intersection of empty boxes could be non-empty. This is a very low-level change, and in such situations usually all hell breaks loose. Luckily that is not the case, save for Correlation.cc in VW. That one has very dense code that heavily relies on this incorrect functionality, and all our stereo relies on this file. I don't have time now to go deeply into this, so I put on top of this file a copy of the original wrong function for taking the union of boxes to not affect the current results, while all other code in VW and ASP now use the correct function. 

Now that the issue is localized to a single file (which took forever to figure out given how low-level this functionality is and how long it takes to compile), hopefully at some point in the future this algorithm will be studied in careful detail and it will be adapted to use the correct way of merging boxes.

**Comment by ScottMcMichael** [comment]
I tested this out and found that correcting the function produces essentially zero changes in our results so I went ahead and removed the bad grow function.  There is probably some improvement that could be done in the zone subdivision function now that this issue is removed but I don't expect that it would speed things up much.

Removed in VW commit: dae42b145013bdc35f0cf47cb590882e66ae0690
