### ISSUE TITLE
dem_mosaic should support NaN as a nodata value

### ISSUE THREAD

**Issue by SmithB** [NeoGeographyToolkit/StereoPipeline#164]
When dem_mosaic is given input DEMs with NaN as a nodata value, it returns:

"The no-data value cannot be represented exactly as a float. Changing it to the smallest float."

It seems like it should be able to handle NaN as nodata.

**Comment by oleg-alexandrov** [comment]
This is a good point. I spent some time looking at this. The mosaicking tool on its own is not hard to fix. I am experiencing problems writing a GDAL file with a NaN no-data. Getting to the bottom of this will require some time, and the problem could even be in GDAL itself rather than our wrapping on it (though I think it is in the latter). I hope to get this at some point later.  Overall, NaNs are hard to consistently get right, as they disobey normal rules of comparison. 

For now I think dem_mosaic does not choke on NaNs, but simply converts them to the smallest float, which is declared to be the new non-data value. You can recover back the NaN in post-processing using gdalwarp, for example. I will keep this issue in mind.
