### ISSUE TITLE
mgm/sgm on hirise pair, possibly fixed in master but need new release 

### ISSUE THREAD

**Issue by AndrewAnnex** [NeoGeographyToolkit/StereoPipeline#169]
So I have tested both mgm and sgm from the 2.6.0 release on a small patch of a HiRISE pair and the results were very interesting! I want to test making a full sized DEM but I ran into some issues running `parallel_stereo` on the full image extent with some checks within `stereo_corr.cc`  which may have been fixed by later commits 97a1ec2074222d665b98e100e13eabcb331795a4 and 2afad06a98e80e1d87eff5a4bafef302cbc02dd2.

Could a 2.6.1 release of ASP be made soon that includes these fixes? Building ASP will be problematic as I don't have full admin access on the system I run it on, but I could probably build on a different machine that I do have full control of.

**Comment by ScottMcMichael** [comment]
Can you try out the latest daily build and see if it fixes these issues?
https://byss.arc.nasa.gov/stereopipeline/daily_build/

Scott

**Comment by AndrewAnnex** [comment]
oh, didn't think to look for a daily build. will do!

**Comment by AndrewAnnex** [comment]
so far it appears to be working, thanks!

**Comment by oleg-alexandrov** [comment]
Andrew, thank you for testing our stuff. As I recall, our latest version of the 2.6.0 release should have this fix as well. I did not want to make a bugfix release so soon, so I simply overwrote the release files at https://github.com/NeoGeographyToolkit/StereoPipeline/releases. My hope is that the release build there, timestamped 2017-06-01 should have the fix as well, as the fix was applied by me on May 24. That probably means that your release is time-stamed earlier than that.  You could confirm that perhaps if not too hard. And that means hopefully that anybody who did not fetch the release in those early days will now get the corrected version. And yes, we should push out an official bugfix release at some point just to do things the right way.

**Comment by AndrewAnnex** [comment]
Yes, the version of 2.6.0 I had before was time stamped for May 19th. Before trying the nightly version I experimented with different parameters over a small region in a HiRISE pair and concluded that mgm was producing more natural features than sgm in that region and that I did not see much of a benefit going smaller than a 7x7 correlation kernel and I stuck with cost-mode 3.

At a glance both methods are preserving a lot more detail for the things I am interested in (layers) despite taking a lot less time than the local window search, I can email or maybe post here some of the hill shade comparisons and stereo files I made in a day or two.

The nightly release worked and I have managed to make a full DEM using a 7x7 kernel and a 5k corr kernel (which may be a default somewhere in the code, as I set a 4k one in my stereo.default file). 

One suggestion out of this I would have is to add example stereo file to the project/documentation for when using MGM/SGM as a number of options are disabled/ignored.

**Comment by oleg-alexandrov** [comment]
Andrew, I am glad things are working for you. We need to evaluate MGM more, and come up with sensible defaults, and decide how to present that in the doc and the stereo.default file. For now I added a mention of MGM in the tutorial, where stereo params are discussed, with a pointer to the right section describing this in full. We should be able to sort things out before the next release.
