### ISSUE TITLE
stereo_parse error with libpango on ubuntu

### ISSUE THREAD

**Issue by rbeyer** [NeoGeographyToolkit/StereoPipeline#218]
This issue: https://github.com/USGS-Astrogeology/ISIS3/issues/681#issue-398849569 , on the ISIS3 repo, is really an issue for us to deal with here.

**Comment by jlaura** [comment]
@rbeyer it would not surprise me if we run into issues with ASP and ISIS3 in the same conda env and dependency conflicts because of how tightly pinned ISIS3 is to specific versions. As you know, we are working on loosening this. Any issue with someone trying to get ASP building in conda?

**Comment by oleg-alexandrov** [comment]
In this particular case, the problem was different. For some reason, some libraries (whether ISIS or not, I did not check) refused to use the libpango we ship and tried to use the system one which was not compatible. I put a fix, with the build at https://byss.arc.nasa.gov/stereopipeline/daily_build/ having it. I was told the fix works. If there are still issues I will take another look.

**Comment by phil333** [comment]
thx, the different build helped fix the problem
