### ISSUE TITLE
Stereo step: VW error

### ISSUE THREAD

**Issue by WangYuzhe** [NeoGeographyToolkit/StereoPipeline#219]
I tried using the StereoPipeline-2.6.1 to generate a DEM from the WorldView2 images on Ubuntu16.04. A coarse DEM, i.e. SRTM was used for map projection. But ASP failed with a VW error in the stereo step. The error message is "VW error: First Line Time and output from TLC lookup table do not agree of the ephemeris time for the first line of the image."

Could anyone help me fix this problem?

**Comment by oleg-alexandrov** [comment]
I am looking at this and I will try to see if I can improve the error message. for now, I will suggest you run stereo as:

stereo left_mapprojected.tif right_mapproject.tif left_camera.xml right_camera.xml output_prefix/run srtm_dem.tif -t dgmaprpc

where you will use your mapprojected images, your camera xml files, and the SRTM DEM you mapprojected onto. 

I also hope that your images are raw, rather than orthorectified, and that you call them in the right order, which should be left image, right image, left camera, right camera. 

I also looked at where we throw that error. There is a chance your XML file may not be correct. If you have other data, you can try that one. You can open your XML file and see if it has the lines:

<TLCLISTList>
                <TLCLIST>0 0.000000000000000e+00</TLCLIST>
                <TLCLIST>40420 1.684167000000000e+00</TLCLIST>

Let me know how things go. If you still have bad luck, you can try sending me your xml file at the  stereo-pipeline-owner address from our manual, asp_book.pdf that is included with ASP.

**Comment by oleg-alexandrov** [comment]
I wrote you an email. Let me know if you got it or not.

**Comment by oleg-alexandrov** [comment]
Your images are GeoEye. For those, we support the RPC model only. You can invoke our tools with the option -t rpc. The documentation in asp_book.pdf has an example how to process this.

I improved our error reporting to tell the user what I wrote above. I think we just never ran into this situation before.

**Comment by WangYuzhe** [comment]
Thank you Oleg very much. This is a surprise for me. Because I help my colleague process these images which were considered as worldview-2 iamges.

Thanks for your help and time.

**Comment by WangYuzhe** [comment]
Thank you very much for helping me fixing this problem. Now I could generate a DEM from these GeoEye-1 images using ASP. Thanks again for your help and providing such a useful tool.

**Comment by dshean** [comment]
Interesting.  I've processed GE-1 images with the DG linescan model (same workflow as other WV stereo).  Unless ASP recognized this and used the RPC model behind the scenes, although I would expect behavior to exit with error message.  

I was using the output of dg_mosaic (stitching together all subscenes for each catalog ID), which likely cleaned up the XML.  You could try using dg_mosaic for your inputs, and then use try -t dg.

I will note that some of the GE-1 DEMs I've produced contain residual artifacts.  These are likely due to residual issues in the DG linescan model (likely related to the DG acquisition of GeoEye and attempts to use their existing model for a different sensor).  I'll try to remember to do some tests with rpc vs dg session for same inputs, to see if these artifacts are also present in rpc session.

**Comment by oleg-alexandrov** [comment]
That is good to know. ASP will try to use the linescan model from the GE-1 camera file, and if it fails, it will give an error and suggest to use the RPC model. Maybe in the future a deeper study could be done as to why that particular dataset failed.
