### ISSUE TITLE
Adapt image_mosaic approach to mosaic planet labs image tiles

### ISSUE THREAD

**Issue by jchollingsworth** [NeoGeographyToolkit/StereoPipeline#239]
Planet image tiles have bad registration to reach other, and mosaicing them with gdalwarp makes an image which looks visually ok, but if you make any sub-pixel measurements with it you'll retrieve a whole load of nasty mosaicing artifacts.

Maybe we could use the same/similar approach as used in image_mosaic to align and mosaic neighboring planet tiles (either along track or otherwise), so they mosaic with sub-pixel precision.

This would make planet data significantly more useful for optical correlation purposes, especially over larger areas.

Cheers,

James

**Comment by oleg-alexandrov** [comment]
Stitching of Planet files is on our to-do list for this year. We don't know when we will get to it. 

There is a good chance that distortion may play a role when stitching happens, even with accurate alignment. We won't know until we do that. 

In principle, now one could invoke bundle_adjust on the entire image set (arrange so that each image overlaps only with the next several ones), followed by mapprojection on some datum. After that dem_mosaic could be used. It should create a mosaicked orthoimage with hopefully not too many artifacts. I am aware here we want to get a raw image, not an orthoimage. The point is that likely the new tool will function a lot like bundle_adjust in determining a set of rotations/translations that brings n images together based on a set of overlaps.

**Comment by jchollingsworth** [comment]
I see... That all makes a lot of sense. I guess with bundle_adjust you
could also try and solve for distortion, if that's an issue (?... though
ortho images will pose a problem). Ok... I look forward to this development
:) good luck!

J
