### ISSUE TITLE
Detect parallel rays in stereo_tri

### ISSUE THREAD

**Issue by ScottMcMichael** [NeoGeographyToolkit/StereoPipeline#249]
In stereo_tri it can be confusing when all of the points are thrown out because the rays are too close to parallel since there is no warning or error, you just get an empty point cloud.  It would be helpful to count how many rays are discarded because of this and print something to describe what is going on.

**Comment by oleg-alexandrov** [comment]
stereo and bundle_adjust now save the convergence angle for the rays (for stereo it is also printed on screen). This should help debug such problems. (https://stereopipeline.readthedocs.io/en/latest/examples/stereo_pairs.html)

There's also the option --min-triangulation-angle in stereo  (https://stereopipeline.readthedocs.io/en/latest/stereodefault.html#post-processing-triangulation)

Given how large the triangulated points clouds are, it is not feasible to infer statistics about this. This should also be a rare occurrence since normally input data form a stereo pair.
