### ISSUE TITLE
Ninja error when building isis library.

### ISSUE THREAD

**Issue by dreamerhuming** [NeoGeographyToolkit/StereoPipeline#305]
Recently I'm trying to build asp based on Ubuntu 18.04 according to INSTALLGUIDE. When I came to build isis library:
<img width="843" alt="截屏2020-03-27下午11 07 41" src="https://user-images.githubusercontent.com/20228560/77770175-d088b880-707f-11ea-880c-2ad282c53f7e.png">

...negleting compile process...
and a Ninja error occurred:
<img width="432" alt="截屏2020-03-27下午10 58 31" src="https://user-images.githubusercontent.com/20228560/77770207-dbdbe400-707f-11ea-8880-97f923b60bc4.png">

The done.txt shows successful library builds:
<img width="154" alt="截屏2020-03-27下午11 03 57" src="https://user-images.githubusercontent.com/20228560/77769945-7be53d80-707f-11ea-84d9-60699de056b0.png">

Hoping for a solution to the issue. Thanks.

**Comment by oleg-alexandrov** [comment]
ISIS is a dependency of ours. It can be a pain to build and takes a long
time. I am surprised you got so far in the build process. I wonder what
your error was. Mine was often due to C++ ABI incompatibility (e.g., an
error would be: cannot link to function myfun(std::string ....) ).

You should not need to build ASP from source, as we provide binary releases
for Linux and Mac.
