### ISSUE TITLE
stereo_tir running slowly

### ISSUE THREAD

**Issue by yunfancui** [NeoGeographyToolkit/StereoPipeline#322]
I try to run the data processing example for HiRISE in asp_book 11.2. The stage triangulation spends more than 20 hours, but other stage only spend 2 hours in total. 

Skip  step of cam2map4stereo.py, the time spend by triangulation is greatly reduced.

Is there something wrong with the application build by myself?

Thank you.

**Comment by oleg-alexandrov** [comment]
You should use parallel_stereo instead of stereo. I updated this in the doc at that location and many related places. Thanks for pointing this out. 

The reason this takes so long is because the triangulation step is single-threaded, unlike the other ones, which is something we inherited from ISIS.

BTW, you can also run stereo from stereo_gui, which will allow one to select some clips on which to run things, if desired to get a quick result.

**Comment by yunfancui** [comment]
Thank you very much.
