### ISSUE TITLE
Processing CTX example for jitter_solve still shows some remaining jitter

### ISSUE THREAD

**Issue by swalterfub** [NeoGeographyToolkit/StereoPipeline#396]
We have created a sample example for our study area using the new `jitter_solve` program. The results look quite good, improvements are clearly visible. We had to remove the `num-lines-per-position` and the `num-lines-per-orientation` to get any improvements over the plain `bundle_adjust` solutions, though.

So I would like to ask if there is still room for improvements through parameter tuning? We have created a repo for our example under [https://github.com/planetary-fub/asp-jitter_solve-example](https://github.com/planetary-fub/asp-jitter_solve-example).

Here are two figures from our resulting analysis:
![image](https://user-images.githubusercontent.com/17708084/232741515-d77153b5-9629-4fbf-bbf4-21c6fd30a6ef.png)

We plan to submit this example for public discussion to the 6th PDW. Of course we would add you as co-author. Thanks for any suggestion or comments!

**Comment by oleg-alexandrov** [comment]
Thank you for playing with the tool. Yes, I can still see some residual jitter. 

I looked at your script. The workflow is plausible. I am curious what would happen if one really use very fine sampling of poses, so putting back --num-lines-per-position and --num-lines-per-orientation, but instead of 1000 one could use 10-20 or so? 

You can also look at the second example, further down, https://stereopipeline.readthedocs.io/en/latest/tools/jitter_solve.html#example-2-worldview-3-digitalglobe-images-on-earth. That one also uses --num-anchor-points-extra-lines to help at first and last lines. 

Then, perhaps one could use more dense match points (--num-matches-from-disp-triplets) but that is guesswork. 

Also, some of the remaining signal appears to have a non-jitter component too.

As to being a co-author, that is not a requirement in any way, of course. The tools are out there to be used and we're happy when they work.

**Comment by oleg-alexandrov** [comment]
I also see in the newly created DEM some artifacts which likely come from the jitter solver being a bit overzealous. It is not clear what the magnitude is, and if changing the sampling rate or other params may make it go away.

The danger with giving free reign to individual linescan poses is that they can overfit. In an ideal world one would have several other images with a different along-track trajectory, so then the artifacts that are parallel to the image rows would not be parallel to each other in different image pairs, which will constrain the problem. The tool does support more than two images but it becomes trickier to set up the problem as need pairwise matches for any two input images in the set.

**Comment by swalterfub** [comment]
Thanks for your suggestions! I tried some variations of the --num-lines-per-position and --num-lines-per-orientation parameters, but the results look rather scary (see Figures). By increasing the parameters to up to 200, the results get closer to the first one above, but don't really show an improvement - do you think it's worth doing more tests with higher values?

--num-lines-per-position 10 --num-lines-per-orientation 10
![stereo_jitter-10-10](https://user-images.githubusercontent.com/17708084/236289833-611a6e7c-d309-4971-bcc3-1e3262297490.png)

--num-lines-per-position 20 --num-lines-per-orientation 20
![stereo_jitter-20-20](https://user-images.githubusercontent.com/17708084/236289862-59f662e2-7db7-4d6e-b201-9a011340e8e5.png)

--num-lines-per-position 50 --num-lines-per-orientation 50
![stereo_jitter-50-50](https://user-images.githubusercontent.com/17708084/236289870-0468184f-f886-4955-a0c0-f6f9a5cc8152.png)

--num-lines-per-position 100 --num-lines-per-orientation 100
![stereo_jitter-100-100](https://user-images.githubusercontent.com/17708084/236289875-7e81b074-d282-416e-ba55-688b7f512431.png)

--num-lines-per-position 200 --num-lines-per-orientation 200
![stereo_jitter-200-200](https://user-images.githubusercontent.com/17708084/236289887-ca5cc255-5709-4125-939a-d98055eee88e.png)

**Comment by oleg-alexandrov** [comment]
Giving it too much flexibility seems to be causing problems.

At the end of the day, this tool is meant to fix the worst problems. Having a side-by-side figure of intersection error before and after the tool, with same colorbar range, can give users a chance to judge if the performance of the tool is good enough for their goals. You do have such a plot earlier.

At least as important as the intersection error is if artifacts are introduced in the DEM, so one could try to quantify those somehow, maybe using a difference plot, as a hillshaded image may show artifacts but it may not be clear what the magnitude is.

**Comment by swalterfub** [comment]
Thank you for your valuable comments! We will try to continue with multiple coverage, as an outlook!

**Comment by oleg-alexandrov** [comment]
Sure. When I revisit jitter work I will play more with your example. Thanks again for trying out the tool. Maybe one day it will have some use.

**Comment by swalterfub** [comment]
It already has! Thanks for providing all these fantastic DTM-generation tools!

**Comment by oleg-alexandrov** [comment]
I found time to look at this jitter_solve problem for CTX. 

The solution here is to have a high enough heights-from-dem-uncertainty to account for the very rough MOLA DEM (463 m/pixel) and the very steep, poorly-resolved terrain around the large crater, while keeping a tight camera-position-uncertainty (camera position is not the problem here). One also needs a fine pose sampling to fit the oscillation, and anchor points to not let this go wild. 

Here is the command that worked:

```
jitter_solve \
  left.cub right.cub left.json right.json \
  --input-adjustments-prefix ba_align/run \
  --match-files-prefix stereo/run-disp \
  --max-pairwise-matches 100000 \
  --max-initial-reprojection-error 20 \
  --num-iterations 30 \
  --num-lines-per-position 1000 \
  --num-lines-per-orientation 250 \
  --heights-from-dem ref_dem.tif \
  --heights-from-dem-uncertainty 300 \
  --heights-from-dem-robust-threshold 0.05 \
  --camera-position-uncertainty 100,100 \
  --num-anchor-points 1000 \
  --num-anchor-points-extra-lines 5000 \
  --anchor-dem ref_dem.tif \
  --anchor-dem-uncertainty 300 \
  --tri-weight 0.1 \
  -o jitter/run
```

<img width="1006" height="829" alt="Image" src="https://github.com/user-attachments/assets/8fbb33d6-62b4-4133-ab85-8b1084b86fb4" />

<img width="714" height="863" alt="Image" src="https://github.com/user-attachments/assets/a8482f50-0839-4c16-8311-286a7628a291" />

The triangulation error is well-below the 6 m/pixel GSD, apart from steep areas, to be dealt with below with mapprojection.

<img width="1038" height="851" alt="Image" src="https://github.com/user-attachments/assets/a238f3b9-029c-46d5-9980-ea50f7e61699" />

Here, the baseline is the before result, so CTX DEM before solving for jitter. The only claim we can make here is that the post-jitter-solve DEM became more consistent with MOLA and more internally consistent without changing drastically. More robust results would use more than one CTX pair, and likely with scan lines that intersect at some angle as that constains the problem better.

The remaining artifacts are due to the steep crater rim. To fix those, the DEM produced above was blurred a little, the jitter-solve cameras were used for mapprojection on it, and stereo was redone with mapprojected images. Here is the result.

<img width="685" height="789" alt="Image" src="https://github.com/user-attachments/assets/e1e95399-9a1e-4266-8f44-498590cc2a10" />

<img width="1142" height="903" alt="Image" src="https://github.com/user-attachments/assets/e42935bb-1f18-4804-91c6-ba889f0c1e70" />

Now, some small pattern is still seen parallel to scan lines. I'd say it is minor. It shows up only in the tri image and does not appear as a seam in the DEM. Note that point2dem tends to cut off that region with higher tri error based on its internal tri error outlier estimation, so it should be called with an explicit outlier cutoff value, so with an option such as --max-valid-triangulation-error 10 or something.

I am in the process of having the CTX documentation for jitter_solve updated with these params too as it works there as well for the different dataset in there.
