### ISSUE TITLE
hiedr2mosaic.py divergent between conda and release build

### ISSUE THREAD

**Issue by Hyradus** [NeoGeographyToolkit/StereoPipeline#406]
**Describe the bug**
We noticed that the hiedr2mosaic.py provided by the github release build is different from the one provided by conda installation.

**edited after additional findings**

In detail:
a "--web" option has been added hiedr2mosaic.py in ASP 3.1.0, to be used by spiceinit.   [3.1.0 release notes](https://stereopipeline.readthedocs.io/en/latest/news.html#release-3-1-0-may-18-2022)
* 3.1.x from github release builds, the option **is not available** 
* 3.2.x from github release builds, the option **is not available** 
* 3.1.x or above from conda -c nasa-ames-stereo-pipeline, the option **is not available** 
* [2023-07-11-daily-build](https://github.com/NeoGeographyToolkit/StereoPipeline/releases/tag/2023-07-11-daily-build) the option **is available**
* Checking the latest master branch [hiedr2mosaic.py](https://github.com/NeoGeographyToolkit/StereoPipeline/blob/master/src/asp/Tools/hiedr2mosaic.py) the option **is available** 

So ti seems that the daily build has the option but the version builds not.

**To Reproduce**
Install ASP using conda channel nasa-ames-stereo-pipeline
or
Use precompiled binaries 3.1.0, 3.2.0

**Expected behavior**
hiedr2mosaic.py should accept --web option

**Your Environment (please complete the following information):**
 - OS: Archcraft/Ubuntu/Windows/Docker
 - ASP Version: 3.1.0+

**Additional context**
I don't know how conda builds are made, but I think it may be a problem to have divergent versions.

**Comment by rbeyer** [comment]
The `--web` option has been added to the "Changes since last release" notes after the 3.2.0 release, and the changes to the codebase that added it were made in January 2023.  It is not in the 3.1.0 release notes (released May 2022) nor in the 3.2.0 release notes (December 2022) because the changes occurred after those releases.  The NEWS file is constructed in reverse chronological order such that the most recent things are at the top and the oldest items are at the bottom.

This feature has been added to the codebase, but is not yet present in a versioned release, so your observation that "the daily build has the option but the version builds not" is absolutely correct, and not at all divergent.

**Comment by Hyradus** [comment]
Ahhh! Got it, thanks! My understanding of the release notes order was completely divergent :)  
Is there a timeline for the next complete release?

**Comment by oleg-alexandrov** [comment]
Not sure about when we'll have an official release. Sometimes this Fall,
before October, even. The daily build seems to be working reasonably well
as a snapshot of latest functionality.
