### ISSUE TITLE
Updating usgscsm's installation location

### ISSUE THREAD

**Issue by chkim-usgs** [NeoGeographyToolkit/StereoPipeline#420]
Hello,

There has been a recent update to usgscsm regarding a change in the library installation path (https://github.com/DOI-USGS/usgscsm/pull/467). We would like to coordinate with the ASP team as to when we should cut the next usgscsm release which will include this path change and open communication for any further discussion regarding so.

Thanks.

**Comment by oleg-alexandrov** [comment]
For ASP this change in usgscsm will not be an issue until ASP makes a new release using the updated usgscsm. 

I am guessing the order of things may be for a new usgscsm package to be released, then a new ISIS version to be released too, as  ISIS will have to change to take into account the new installation path. Then ASP will have to make appropriate adjustments before making a release. 

So, I think the scheduling should be on your side and you can let me know when things are ready so that ASP can catch up.

**Comment by chkim-usgs** [comment]
Sounds good! Will keep you in the loop regarding the upcoming usgscsm and ISIS releases.

**Comment by chkim-usgs** [comment]
Hello, [usgscsm 2.0.0](https://github.com/DOI-USGS/usgscsm/releases/tag/2.0.0) has been released with the change in library path and [ISIS 8.1.0_RC2](https://github.com/DOI-USGS/ISIS3/tree/8.1.0_RC2) was released accordingly with an [update to IsisPreferences](https://github.com/DOI-USGS/ISIS3/blob/8.1.0_RC2/isis/IsisPreferences#L181).

**Comment by oleg-alexandrov** [comment]
Thank you. I will wait till an official 8.1.0 release is out, including the conda packages, and then later will make an ASP release tied to that.
