### ISSUE TITLE
Question about ASP Resolution

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [NeoGeographyToolkit/StereoPipeline#429]
Hi there, I am curious about the highest achievable vertical resolution with Stereo Pipeline. Say I have two images with 1 meter/pixel resolution in lat lon, does that mean that the height resolution is also 1 meter? Or something less?

Thanks!

**Comment by oleg-alexandrov** [comment]
The vertical resolution is very dependent on the convergence angle. As a rule of thumb, if you have a convergence angle of say 30-60 degrees, a vertical resolution of 2-3 meters looks achievable, given an input horizontal resolution of 1 m. With ASP it is suggested, for best results, to mapproject at 1 m/pixel in a local projection then use the asp_mgm algorithm.

**Comment by jlaura** [comment]
@oleg-alexandrov Do know of a paper/reference that discusses the mathematics of this? I am interested in providing more detailed metadata for ASP generated DTMs and since one knows all of the view geometry, it should be possible to estimate the vertical resolution (I think?).

Thanks!

**Comment by rbeyer** [comment]
The earliest reference I can find that talks about expected vertical precision is [Cook et al. (1996, section 3.2)](https://doi.org/10.1016/S0032-0633(96)00061-X), but I feel like this is probably discussed before 1996, but maybe not?  Randy also uses this formulation in [Kirk et al. (2003, para 38)](https://doi.org/10.1029/2003JE002131).  And purveyors of terrain models have used it since.  

However, this is really a predictive measure: what is expected?  Frequently, the actual data will result in vertical precisions that can vary from a value computed this way.  The recent [Bland et al. (2021)](https://doi.org/10.3390/rs13245097) talks about applying this and how expected vertical precision is kidn of only one relevant metric.

**Comment by jlaura** [comment]
@rbeyer Thanks for the Kirk reference and I had totally forgotten about Mike's paper. I'll be re-reading... :) Much appreciated
