### ISSUE TITLE
Have ASP produce stereo at lower resolution than the input images

### ISSUE THREAD

**Issue by oleg-alexandrov** [NeoGeographyToolkit/StereoPipeline#43]
It would be desirable to have stereo output a point cloud at say 2x coarser resolution than the input images. To implement that, one would need to internally sub-sample the input images and scale accordingly the cameras. The scaling of images is trivial, the scaling of the cameras could be achieved by very small modifications to the point_to_pixel(), pixel_to_vector() and camera_center() functions, regardless of camera type. 

This is not urgent, I put it here to make sure we don't forget.

**Comment by rbeyer** [comment]
This issue is quite old, and if we have a solution, or this is no longer an issue, then it should be closed.  

However, as I sit here in 2020, it seems like you can either downsample the input images if you don't want `stereo` to work as hard, or use options on `point2dem` or `point2mesh` to adjust the scaling on the produced products.

**Comment by ScottMcMichael** [comment]
We still get requests for this feature, I did not realize we have been putting it off since 2013 =)

**Comment by oleg-alexandrov** [comment]
ASP now produces by default a PC_sub.tif, which is one-to-one with D_sub.tif, and whose size is about 300 to 600 pixels on the side. Not quite what is asked here, but I don't think this will get implemented.
