### ISSUE TITLE
bundle adjustment of RPC model

### ISSUE THREAD

**Issue by kyuhyoung** [NeoGeographyToolkit/StereoPipeline#443]
Hello.  
This software seems to be huge.  I took a look to see if this software provides a way to bundle adjustment of RPC camera model for pushbroom-style imaging (NOT RPC distortion model of pin-hole camera) just like [https://github.com/centreborelli/sat-bundleadjust](https://github.com/centreborelli/sat-bundleadjust).
After reading "Bundle Adjustment" document ([https://github.com/NeoGeographyToolkit/StereoPipeline/blob/master/docs/bundle_adjustment.rst](https://github.com/NeoGeographyToolkit/StereoPipeline/blob/master/docs/bundle_adjustment.rst)), I think ASP does not support for the bundle adjustment of RPC camera model. 
Am I right ?  
I just want to use ASP instead of sat-bundleadjust since ASP seems to be stable and has more features.
Is there any way of RPC model bundle adjustment from ASP.

**Comment by oleg-alexandrov** [comment]
ASP supports bundle-adjusting RPC cameras, by applying an external position
and orientation adjustment to each camera, rather than modifying the RPC
coefficients directly.

There is an example here:
https://stereopipeline.readthedocs.io/en/latest/tools/bundle_adjust.html

How to later do stereo is described here:
https://stereopipeline.readthedocs.io/en/latest/examples/rpc.html#rpc

**Comment by kyuhyoung** [comment]
Thanks for quick reply.  I will check.
